# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.

# Get result
# flutter pub run dart_code_metrics:metrics analyze lib    


##################### Standart flutter linter #####################

# include: package:flutter_lints/flutter.yaml


# linter:
#   rules:
#     avoid_print: false  
#     prefer_single_quotes: true  #
#     always_use_package_imports: true
#     avoid_dynamic_calls: true
#     avoid_empty_else: true
#     avoid_relative_lib_imports: true

##################### Standart flutter linter #####################

include: package:extra_pedantic/analysis_options.yaml

linter:
  # All rules: https://github.com/dart-lang/linter/blob/master/lib/src/rules.dart
  rules:
    prefer_relative_imports: false
    use_build_context_synchronously: false  # TODO Is it possible to check if context is mounted? :(
    comment_references: false
    sort_pub_dependencies: false

    sort_child_properties_last: true
    leading_newlines_in_multiline_strings: true
    no_runtimeType_toString: true
    unnecessary_null_checks: true
    use_if_null_to_convert_nulls_to_bools: true
    use_key_in_widget_constructors: true
    use_late_for_private_fields_and_variables: true
    require_trailing_commas: true


analyzer:
  ### extra_pedantic ###
  strong-mode:
      # https://github.com/dart-lang/language/tree/master/resources/type-system
      implicit-casts: false
      implicit-dynamic: true
  language:
    # https://github.com/dart-lang/language/tree/master/resources/type-system
    strict-inference: true
    strict-raw-types: true
    strict-casts: true
  errors:
    inference_failure_on_function_invocation: false
  ### extra_pedantic ###

  plugins:
    - dart_code_metrics
  exclude:
    - '**/*.g.dart'
    - '**/*.freezed.dart'
    - '**/*.gr.dart'
    - lib/generated/**

dart_code_metrics:
  metrics:
    cyclomatic-complexity: 10
    halstead-volume: 500
    lines-of-code: 80
    maintainability-index: 40
    maximum-nesting-level: 5
    number-of-methods: 10
    number-of-parameters: 8
  metrics-exclude:
    - test/**
    - lib/setup.dart
  rules:
    # Common rules
    - no-boolean-literal-compare
    - no-empty-block
    - prefer-trailing-comma
    - prefer-first
    - prefer-last
    - no-equal-then-else
    # Flutter specific
    - avoid-border-all
    - avoid-returning-widgets
    - avoid-unnecessary-setstate
    - avoid-wrapping-in-padding
    - prefer-const-border-radius
    - prefer-extracting-callbacks
    - prefer-single-widget-per-file:
        ignore-private-widgets: true
  anti-patterns:
    - long-method
    - long-parameter-list