############################################################################
# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.

# Get result
# fvm dart run dart_code_linter:metrics analyze lib
############################################################################

analyzer:
  plugins:
    - dart_code_linter
  exclude:
    - 'packages/rust_lzss/cargokit/**'
    - '**/*.g.dart'
    - '**/*.freezed.dart'
    - '**/*.gr.dart'
    - '**/__generated__/**'

dart_code_linter:
  extends:
      - package:dart_code_linter/presets/all.yaml
  metrics:
    cyclomatic-complexity: 10
    number-of-parameters: 8
    maximum-nesting-level: 5
  metrics-exclude:
    - test/**
  rules:
    - avoid-dynamic: false
    - avoid-non-null-assertion: false
    - format-comment: false
    - avoid-ignoring-return-values: false
    - prefer-static-class: false
    - member-ordering: false
    - prefer-moving-to-variable: false
    - no-magic-number: false
    - prefer-single-widget-per-file: false
