name: threedpass
description: A 3dpass application.

publish_to: 'none' 

# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  ## UI
  three_dart: ^0.0.11
  three_dart_jsm: ^0.0.6
  flutter_gl: ^0.0.18
  flutter_platform_widgets: ^2.0.0
  
  flutter_markdown: ^0.6.10+3
  url_launcher: ^6.1.5
  file_picker: ^5.0.1
  qr_flutter: ^4.0.0
  flutter_svg: ^1.1.1+1
  fluttertoast: ^8.0.9
  expandable: ^5.0.1

  ## Core
  auto_route: ^4.2.1
  ffi: ^2.0.1
  calc:
    path: packages/calc
  get_it: ^7.2.0
  flutter_bloc: ^8.0.1
  # flutter_form_bloc: ^0.30.1  # Use reactive forms instead
  provider: ^6.0.3
  hive_flutter: ^1.1.0
  polkawallet_sdk: ^0.4.9
  

  ## Code gen
  copy_with_extension: ^4.0.2
  freezed: ^2.1.0+1
  equatable: ^2.0.3

  ## Utils
  intl: ^0.17.0
  easy_localization: ^3.0.1
  share_plus: ^4.0.10
  logger: ^1.1.0
  flutter_keyboard_visibility: ^5.3.0

  ## Special
  webview_flutter: ^3.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  hive_generator: ^1.1.2
  copy_with_extension_gen: ^4.0.1
  build_runner:
  auto_route_generator: ^4.2.0
  flutter_launcher_icons: ^0.9.3
  change_app_package_name: ^1.1.0
  
  flutter_lints: ^1.0.4
  dart_code_metrics: ^4.16.0

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/wallet/
    - assets/textures/
    - assets/translations/

