name: threedpass
description: A 3dpass application.

publish_to: 'none' 

# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.18.0+49

environment:
  sdk: ">=3.0.6 <4.0.0"
  flutter: "3.24.0"

dependencies:
  flutter:
    sdk: flutter

  ## UI
  flutter_screen_lock: ^9.0.1
  flutter_svg: ^2.0.7
  fluttertoast: ^8.2.2
  infinite_scroll_pagination: ^4.0.0
  shimmer: ^3.0.0
  unicons: ^2.1.0
  url_launcher: ^6.1.12
  file_picker: ^8.1.2
  qr_flutter: ^4.1.0
  package_info_plus: ^8.0.2
  
  ## Core
  auto_route: ^8.1.4
  ffi: ^2.0.1
  get_it: ^7.6.0
  flutter_bloc: ^8.1.3
  path_provider: ^2.1.0
  hive: ^2.2.3
  isar: 3.1.0+1 # TODO Move to isar 4.0.0-dev.14
  isar_flutter_libs: 3.1.0+1 # contains Isar Core
  flutter_inappwebview: ^5.7.2+3
  polkawallet_sdk: #0.5.1
    # path: ../polkawallet_sdk
    git:
        url: https://github.com/L3odr0id/polkawallet_sdk.git
        ref: e1e722ee506de0397e86b246bb5968ca2e084f98 # release/0.5.1 # branch name
  decimal: ^2.3.3
  rational: ^2.2.3
  async: ^2.11.0
  hashlib: ^1.21.0
  dio: ^5.8.0+1
  # fpdart: ^1.1.0

  ## Code gen
  copy_with_extension: ^5.0.3
  freezed_annotation: ^2.4.4
  equatable: ^2.0.5
  json_annotation: ^4.9.0 

  ## Utils
  intl: ^0.19.0
  easy_localization: ^3.0.2
  # share_plus: ^4.0.10
  logger: ^2.4.0
  mask_text_input_formatter: ^2.4.0
  number_text_input_formatter: ^1.0.0+8
  flutter_phoenix: ^1.1.0 # TODO REMOVE
  app_install_date: ^0.1.5
  scrollview_observer: ^1.20.0

  # Child packages
  rust_lzss:
    path: ./packages/rust_lzss

  # Graphql
  ferry: ^0.16.0+1
  ferry_hive_store: ^0.5.2
  gql_http_link: ^1.1.0
  hive_flutter: ^1.1.0

dev_dependencies:
  # integration_test:
  #   sdk: flutter
  flutter_test:
    sdk: flutter

  ## Generators
  build_runner:
  hive_generator: ^2.0.0
  isar_generator: 3.1.0+1
  copy_with_extension_gen: ^5.0.3
  auto_route_generator: ^8.0.0
  freezed: ^2.5.2
  json_serializable: ^6.3.1
  ferry_generator: ^0.12.0
  gql_code_builder: ^0.13.0

  ## Dev utils
  flutter_launcher_icons: ^0.13.1
  
  ## Linters
  flutter_lints: ^4.0.0
  dart_code_linter: ^1.3.0

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/wallet/
    - assets/textures/
    - assets/translations/

    - test/resources/

