name: threedpass
description: A 3dpass application.

publish_to: 'none' 

# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.16.0+41

environment:
  sdk: ">=3.0.6 <3.3.5"

isar_version: &isar_version 3.1.0+1 # define the version to be used

dependencies:
  flutter:
    sdk: flutter

  ## UI
  # three_dart: ^0.0.16
  three_dart: # TODO Remove
    git:
        url: https://github.com/L3odr0id/three_dart.git
        ref: 695b58ab4ef889c4f472fb79420a36134974da5e # mobile-branch # branch name
  # three_dart_jsm: ^0.0.10
  three_dart_jsm: # TODO Remove
    git:
      url: https://github.com/L3odr0id/three_dart_jsm.git
      ref: b6c8e5fcf876151d601ab092fe7fc94901edb446
  flutter_gl: ^0.0.18 # TODO Remove
  flutter_platform_widgets: ^3.3.5 # TODO Remove
  flutter_screen_lock: ^9.0.1
  flutter_svg: ^2.0.7
  fluttertoast: ^8.2.2
  infinite_scroll_pagination: ^3.2.0
  badges: ^3.1.1 # TODO Remove
  shimmer: ^3.0.0
  
  unicons: ^2.1.0
  url_launcher: ^6.1.12
  file_picker: ^5.3.3
  qr_flutter: ^4.1.0
  package_info_plus: ^4.1.0
  
  ## Core
  auto_route: ^7.5.0
  ffi: ^2.0.1
  calc:
    path: packages/calc
  get_it: ^7.6.0
  flutter_bloc: ^8.1.3
  # flutter_form_bloc: ^0.30.1  # Use reactive forms instead
  provider: ^6.0.5
  path_provider: ^2.1.0
  hive: ^2.2.3
  isar: *isar_version
  isar_flutter_libs: *isar_version # contains Isar Core
  flutter_inappwebview: ^5.7.2+3
  polkawallet_sdk: #0.5.1
    # path: ../polkawallet_sdk
    git:
        url: https://github.com/L3odr0id/polkawallet_sdk.git
        ref: 45564145bc771e0d881401503a2726260e7902b0 # release/0.5.1 # branch name
  decimal: ^2.3.3
  rational: ^2.2.3

  ## Code gen
  copy_with_extension: ^5.0.3 # TODO REMOVE. Use only freezed
  freezed: ^2.3.5
  equatable: ^2.0.5 # TODO REMOVE. Use only freezed
  json_annotation: ^4.8.1 # TODO REMOVE. Use only freezed

  ## Utils
  intl: ^0.18.0
  easy_localization: ^3.0.2
  share_plus: ^4.0.10
  logger: ^1.1.0
  mask_text_input_formatter: ^2.4.0
  number_text_input_formatter: ^1.0.0+8
  flutter_phoenix: ^1.1.0 # TODO REMOVE
  app_install_date: ^0.1.3
  scrollview_observer: ^1.20.0

  # Child packages. # TTODO Move all to main app
  super_core:
    path: ./packages/super_core
  threedp_graphql:
    path: ./packages/threedp_graphql

  gql_code_builder: ^0.6.0 # Fix compilations. Do not remove

dev_dependencies:
  # integration_test:
  #   sdk: flutter
  flutter_test:
    sdk: flutter

  ## Generators
  hive_generator: ^2.0.0
  isar_generator: *isar_version
  copy_with_extension_gen: ^5.0.3 # TODO REMOVE. Use only freezed
  build_runner:
  auto_route_generator: ^7.1.1
  json_serializable: ^6.3.1 # TODO REMOVE. Use only freezed

  ## Dev utils
  flutter_launcher_icons: ^0.9.3
  
  ## Linters
  flutter_lints: ^1.0.4
  dart_code_metrics: ^5.7.5 # TODO MOVE TO https://github.com/rei-codes/dart-code-metrics
  extra_pedantic: ^3.0.0

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/wallet/
    - assets/textures/
    - assets/translations/

    - test/resources/

