name: threedpass
description: A 3dpass application.

publish_to: 'none' 

# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.5.0+21

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # logger_flutter:
  #   git:
  #     url: https://github.com/alphapokedex/logger_flutter.git

  ## UI
  # three_dart: ^0.0.16
  three_dart: 
    git:
        url: https://github.com/L3odr0id/three_dart.git
        ref: 695b58ab4ef889c4f472fb79420a36134974da5e # mobile-branch # branch name
  # three_dart_jsm: ^0.0.10
  three_dart_jsm:
    git:
      url: https://github.com/L3odr0id/three_dart_jsm.git
      ref: b6c8e5fcf876151d601ab092fe7fc94901edb446
  flutter_gl: ^0.0.18
  flutter_platform_widgets: ^2.0.0
  infinite_scroll_pagination: ^3.2.0
  
  unicons: ^2.1.0
  url_launcher: ^6.1.5
  file_picker: ^5.2.5
  qr_flutter: ^4.0.0
  flutter_svg: ^1.1.1+1
  fluttertoast: ^8.0.9
  package_info_plus: ^3.0.3

  ## Core
  auto_route: ^4.2.1
  ffi: ^2.0.1
  calc:
    path: packages/calc
  get_it: ^7.2.0
  flutter_bloc: ^8.0.1
  # flutter_form_bloc: ^0.30.1  # Use reactive forms instead
  provider: ^6.0.3
  path_provider: ^2.0.13
  hive_flutter: ^1.1.0
  polkawallet_sdk: #0.5.1
    git:
        url: https://github.com/L3odr0id/polkawallet_sdk.git
        ref: 5492466fdcb65d2dcc62672cd4672824a47d609f # release/0.5.1 # branch name

  ## Code gen
  copy_with_extension: ^4.0.2
  freezed: ^2.1.0+1
  equatable: ^2.0.3
  json_annotation: ^4.6.0

  ## Utils
  intl: ^0.17.0
  easy_localization: ^3.0.1
  share_plus: ^4.0.10
  logger: ^1.1.0
  flutter_keyboard_visibility: ^5.3.0
  mask_text_input_formatter: ^2.4.0
  flutter_phoenix: ^1.1.0

  # Child packages
  super_core:
    path: ./packages/super_core
  threedp_graphql:
    path: ./packages/threedp_graphql

  gql_code_builder: ^0.6.0 # Fix compilations. Do not remove

dev_dependencies:
  flutter_test:
    sdk: flutter

  ## Generators
  hive_generator: ^1.1.2
  copy_with_extension_gen: ^4.0.1
  build_runner:
  auto_route_generator: ^4.2.0
  json_serializable: ^6.3.1

  ## Dev utils
  flutter_launcher_icons: ^0.9.3
  change_app_package_name: ^1.1.0
  keystore_generator: ^1.0.1
  
  ## Linters
  flutter_lints: ^1.0.4
  dart_code_metrics: ^4.16.0
  extra_pedantic: ^3.0.0

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/wallet/
    - assets/textures/
    - assets/translations/

