[package]
name = "rust_lzss"
version = "0.7.0"
authors = ["l3odr0id"]
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
flutter_rust_bridge = "=2.3.0"
lzss = { version = "0.8", default-features = false, features = ["alloc"] }
p3d = { version = "0.7.0", git="https://github.com/3Dpass/p3d", rev="5eed819" }
