import 'dart:convert';

import 'package:threedp_graphql/features/tokens_events_history/data/query/__generated__/get_tokens_events.data.gql.dart';
import 'package:threedpass/core/polkawallet/app_service.dart';
import 'package:threedpass/core/polkawallet/utils/balance_utils.dart';
import 'package:threedpass/core/polkawallet/utils/decode_address.dart';
import 'package:threedpass/core/polkawallet/utils/encode_address.dart';
import 'package:threedpass/core/polkawallet/utils/find_token_symbol.dart';
import 'package:threedpass/core/polkawallet/utils/network_state_data_extension.dart';
import 'package:threedpass/features/wallet_screen/presentation/non_native_token_screen/domain/entities/asset_history_create.dart';
import 'package:threedpass/features/wallet_screen/presentation/non_native_token_screen/domain/entities/asset_history_mint.dart';
import 'package:threedpass/features/wallet_screen/presentation/non_native_token_screen/domain/entities/asset_history_set_meta_data.dart';
import 'package:threedpass/features/wallet_screen/presentation/non_native_token_screen/domain/entities/asset_history_transfer.dart';
import 'package:threedpass/features/wallet_screen/presentation/non_native_token_screen/domain/entities/asset_history_unknown.dart';

abstract class NonNativeTokenHistoryAtomBase {
  const NonNativeTokenHistoryAtomBase({
    required this.blockDatetime,
    required this.extrinsicIdx,
    required this.authorAddress,
  });

  final DateTime blockDatetime;
  final int extrinsicIdx;
  final String authorAddress;

  NonNativeTokenExtrinsicType get extrinsicType;

  // ignore: long-method
  static Future<NonNativeTokenHistoryAtomBase> fromAutoGeneratedObject(
    final GGetExtrinsicsData_getExtrinsics_objects autoGeneratedObject,
    final AppService appService,
  ) async {
    // final service = appService.plugin.sdk.api.account.service;
    // final ss58Format = appService.networkStateData.ss58Format;
    // autoGeneratedObject.callArguments
    // final fromAccountId = autoGeneratedObject.cal;
    // final toAccountId = autoGeneratedObject.toMultiAddressAccountId;

    final a1 = autoGeneratedObject.callArguments;
    final a2 = jsonDecode(a1!.value) as List;

    final date = DateTime.parse(autoGeneratedObject.blockDatetime?.value ?? '');
    final extrinsicIdx = autoGeneratedObject.extrinsicIdx ?? -1;
    final authorAddress = await appService.encodeAddress(
      autoGeneratedObject.multiAddressAccountId ?? '',
    );

    switch (autoGeneratedObject.callName) {
      case 'create':
        return AssetHistoryCreate(
          blockDatetime: date,
          extrinsicIdx: extrinsicIdx,
          authorAddress: authorAddress,
        );
      case 'set_metadata':
        return AssetHistorySetMetadata(
          blockDatetime: date,
          extrinsicIdx: extrinsicIdx,
          authorAddress: authorAddress,
          name: a2[1]['value'].toString(),
          symbol: a2[2]['value'].toString(),
          decimals: a2[3]['value'].toString(),
        );
      case 'mint':
        return AssetHistoryMint(
          blockDatetime: date,
          extrinsicIdx: extrinsicIdx,
          authorAddress: authorAddress,
          value: a2[2]['value'].toString(),
        );

      case 'transfer':
      case 'transfer_keep_alive':
        final assetId = a2[0]['value'].toString();
        final tokenBalanceData = appService.findTokenBalanceData(assetId);
        final safeDecimals = appService.networkStateData.safeDecimals;
        final isFrom = authorAddress == appService.keyring.current.address;

        final value = a2[2]['value'].toString();
        final targetAccountId = a2[1]['value'] as String;
        final targetAddress = await appService.decodeAddress(targetAccountId);
        print('Decimals:${tokenBalanceData.decimals}');
        return AssetHistoryTransfer(
          blockDatetime: date,
          extrinsicIdx: extrinsicIdx,
          authorAddress: authorAddress,
          value: value,
          isFrom: isFrom,
          targetAddress: targetAddress,
          symbols: tokenBalanceData.symbol ?? '',
          decimals: tokenBalanceData.decimals ?? safeDecimals,
        );

      // break;
      default:
        return AssetHistoryUnkown(
          blockDatetime: date,
          extrinsicIdx: extrinsicIdx,
          authorAddress: authorAddress,
          arguments: autoGeneratedObject.callArguments?.value ?? '',
          callModule: autoGeneratedObject.callModule ?? '',
        );
      // break;
    }
  }
}

enum NonNativeTokenExtrinsicType {
  create,
  set_metadata,
  mint,
  transfer,
  unknown,
}
