[package]
name = "p3d_interface"
version = "0.3.1"
authors = ["l3odr0id"]
edition = "2018"

[build]
target = "wasm32-unknown-unknown"

[lib]
name = "calc"
crate-type = ["staticlib", "cdylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
p3d_0_3_1 = { package = "p3d", tag = "v0.6.0", git = "https://github.com/3Dpass/p3d#4a98da181478ac9ba5e27e96a31a8c695d200c61" }
p3d_0_3_0 = { package = "p3d", tag = "v0.5.0", git = "https://github.com/3Dpass/p3d#91c72dfe7f7bacf5de088009133c64ca2197aef7" }

