part of '../transactions_history_page.dart';

class TransactionItem extends StatelessWidget {
  const TransactionItem({
    required this.object,
    this.colorFromSecondary = false,
    this.colorToSecondary = false,
    super.key,
  });

  final TransferItem object;
  final bool colorFromSecondary;
  final bool colorToSecondary;

  @override
  Widget build(final BuildContext context) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        const SizedBoxH8(),
        _TransactionAmount(
          object.autoGeneratedObject.value!.toInt().toString(),
        ),
        const SizedBoxH8(),
        _ShortAddress(
          prefix: 'From:',
          address: object.fromAddress,
          colorSecondary: colorFromSecondary,
        ),
        const SizedBoxH4(),
        _ShortAddress(
          prefix: 'To:',
          address: object.toAddress,
          colorSecondary: colorToSecondary,
        ),
        const SizedBoxH8(),
        _BlockDatetime(object.autoGeneratedObject.blockDatetime!),
      ],
    );
  }
}

class _TransactionAmount extends StatelessWidget {
  const _TransactionAmount(this.amount);

  final String amount;
  @override
  Widget build(final BuildContext context) {
    final appService = BlocProvider.of<AppServiceLoaderCubit>(context).state;
    final moneyStr = BalanceUtils.balance(
      amount,
      appService.networkStateData.safeDecimals,
    );
    final symbol = appService.networkStateData.tokenSymbol?.first ?? '';
    return D3pBodyLargeText(
      '$moneyStr $symbol',
    );
  }
}

class _ShortAddress extends StatelessWidget {
  const _ShortAddress({
    required this.prefix,
    required this.address,
    required this.colorSecondary,
  });

  final String? address;
  final String prefix;
  final bool colorSecondary;

  @override
  Widget build(final BuildContext context) {
    final addressStr = Fmt.shorterAddress(address, pad: 10);
    final styles = Theme.of(context).customTextStyles;
    return Row(
      children: [
        Flexible(
          child: Text(
            '$prefix $addressStr',
            style: colorSecondary ? styles.secondaryText : styles.d3pBodyMedium,
          ),
        ),
        colorSecondary ? const SizedBox() : _CopyButton(address),
      ],
    );
  }
}

class _BlockDatetime extends StatelessWidget {
  const _BlockDatetime(this.dateTime);
  final GDateTime dateTime;
  @override
  Widget build(final BuildContext context) {
    final dt = DateTime.parse(dateTime.value);
    final fmt = DateFormat('kk:mm – dd-MM-yyyy').format(dt);
    return D3pBodyMediumText(fmt);
  }
}

class _CopyButton extends StatelessWidget {
  const _CopyButton(this.address);

  final String? address;

  void onPressed(final BuildContext context) {
    copyAndNotify(textToCopy: address ?? '');
  }

  @override
  Widget build(final BuildContext context) {
    return IconButton(
      padding: const EdgeInsets.symmetric(horizontal: 8),
      constraints: const BoxConstraints(),
      splashRadius: 25,
      onPressed: () => onPressed(context),
      icon: const Icon(
        Icons.copy,
        size: 20,
      ),
    );
  }
}
