[package]
name = "calc-ffi"
version = "0.1.0"
authors = ["3dpass <3dpass@example.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "calc_ffi"
crate-type = ["cdylib", "staticlib"]

[dependencies]
p3d = { path = "../p3d" }